# Site settings
title: David Miller
header-img: img/home-bg.jpg
email: david@ironsummitmedia.com
description: "The official blog of David Miller, creator of Start Bootstrap and managing partner of Iron Summit Media Strategies"
baseurl: "/davidtmiller-website"
url: "http://davidtmiller.github.io/davidtmiller-website/"
twitter_username: davidmillerskt
github_username:  davidtmiller
facebook_username:  dmironsummit

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
