# Site settings
title: Puppies
header-img: img/home-bg.jpg
email: fightingpuppies@gmail.com
description: "This is my blog"
baseurl: ""
url: "http://puppies.github.io/"
twitter_username: puppies
github_username:  puppies
facebook_username:  puppies

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
